const fs = require('fs');
const path = 'src/lib/tryon/production-tryon-pipeline.ts';
let text = fs.readFileSync(path, 'utf8');
const stage4Start = text.indexOf('        const stage4Start = Date.now()');
if (stage4Start === -1) throw new Error('stage4 not found');
const finalLine = '        finalImage = bufferToBase64(compositeResult.outputBuffer)';
const finalIdx = text.indexOf(finalLine, stage4Start);
if (finalIdx === -1) throw new Error('final line not found');
const prefix =         if (skipPixelOverwrite) {\n            stages.push({\n                stage: 4,\n                name: 'Face Pixel Overwrite',\n                status: 'SKIP',\n                timeMs: 0,\n                data: { reason: 'pixel overwrite disabled for nano-banana-pro' }\n            })\n            finalImage = generatedImage.image\n        } else {\n;
text = text.slice(0, stage4Start) + prefix + text.slice(stage4Start);
const idxAfter = finalIdx + finalLine.length;
text = text.slice(0, idxAfter) + '\n        }' + text.slice(idxAfter);
fs.writeFileSync(path, text, 'utf8');
