import type { TryOnStylePreset, TryOnPresetCategory } from './types'

export const TRYON_PRESETS_V3: TryOnStylePreset[] = [
  {
    id: 'studio_catalog_grey',
    name: 'Studio Catalog (Grey)',
    description: 'Seamless grey backdrop with softbox lighting (e-commerce).',
    category: 'studio',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'studio softbox high key, soft diffused, even illumination',
    background_name:
      'seamless neutral grey studio backdrop, clean commercial look, 85mm portrait lens look, shallow depth of field',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'studio_catalog_white',
    name: 'Studio Catalog (White)',
    description: 'Seamless white cyclorama with clean, neutral color (true-to-fabric).',
    category: 'studio',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'high key studio softbox, even diffuse light, minimal shadows, accurate color rendering',
    background_name: 'seamless white cyclorama studio background, clean product photography look, sharp fabric texture',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },
  {
    id: 'studio_beauty_clamshell',
    name: 'Beauty Clamshell (Studio)',
    description: 'Beauty lighting with soft catchlights; keeps texture realistic (no smoothing).',
    category: 'studio',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'beauty clamshell lighting, soft key + soft fill, gentle shadow under chin, clean separation',
    background_name: 'subtle warm grey studio background, shallow depth of field, premium portrait look',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'studio_rim_moody',
    name: 'Moody Rim Light (Studio)',
    description: 'Low-key studio with rim light separation and cinematic contrast (still photoreal).',
    category: 'studio',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'low key studio, soft key at 45 degrees, subtle rim light, controlled highlights, no halos',
    background_name: 'deep charcoal studio backdrop, cinematic but realistic, natural film grain',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'street_golden_hour',
    name: 'Golden Hour Street',
    description: 'Warm golden hour street with cinematic bokeh.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'golden hour side light, warm soft shadows, natural highlights',
    background_name: 'city street background with shallow depth of field and realistic bokeh',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'street_overcast_soft',
    name: 'Overcast Street (Soft)',
    description: 'Soft overcast daylight for accurate fabric texture.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft overcast daylight, low contrast, accurate colors',
    background_name: 'modern sidewalk with storefronts softly blurred',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'street_flash_night',
    name: 'Night Street Flash',
    description: 'On-camera flash look at night (realistic highlights, no AI glow).',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name:
      'night street with on-camera flash, crisp subject highlights, darker background, realistic shadow falloff, no halos',
    background_name: 'night street scene with subtle bokeh lights, realistic grain, candid flash aesthetic',
    style_pack: 'flash_party',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'street_neon_cyber',
    name: 'Neon Night (Cyan/Magenta)',
    description: 'Cinematic neon rim lights with wet pavement reflections (no extra people).',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name:
      'neon rim lighting: cyan from left, magenta from right, high contrast but realistic, wet reflections, no bloom halos',
    background_name: 'night alley with wet pavement reflections and neon signage in bokeh, realistic atmosphere',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'outdoor_golden_field',
    name: 'Golden Field',
    description: 'Sunlit field with warm cinematic backlight.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'warm sunset backlight with gentle fill, realistic shadows',
    background_name: 'open field with tall grass, shallow depth of field, natural bokeh',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'outdoor_overcast_portrait',
    name: 'Outdoor Overcast (True Color)',
    description: 'Overcast outdoor portrait for accurate garment color and texture.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft overcast daylight, even illumination, accurate color, minimal specular hotspots',
    background_name: 'park walkway background, soft bokeh, natural colors, realistic depth of field',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'outdoor_backlit_sunflare',
    name: 'Backlit Sunflare (Soft)',
    description: 'Gentle backlight with controlled flare (no overexposure).',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name:
      'golden backlight with subtle lens flare, controlled highlights, soft fill on face, realistic shadows',
    background_name: 'outdoor garden background with warm bokeh, cinematic but natural',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'lifestyle_cafe',
    name: 'Lifestyle Café',
    description: 'Cozy café vibe with window light and gentle bokeh.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft window daylight, neutral tones, realistic shadows',
    background_name: 'cozy café terrace background softly blurred',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'lifestyle_home_window',
    name: 'Home Window Light',
    description: 'Indoor home scene with soft window light and realistic texture.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft indoor window light, natural shadows, neutral color, realistic skin texture',
    background_name: 'minimal home interior with warm neutrals, shallow depth of field, realistic atmosphere',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'editorial_architecture',
    name: 'Editorial Architecture',
    description: 'Premium editorial look with clean architectural lines.',
    category: 'editorial',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'directional editorial key light with subtle fill, controlled highlights',
    background_name: 'modern architectural courtyard with clean lines and soft bokeh',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'editorial_hard_light',
    name: 'Editorial Hard Light',
    description: 'Hard editorial key light with strong shape (still photoreal; no halos).',
    category: 'editorial',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'hard key light, crisp shadows, controlled contrast, realistic skin texture, no plastic smoothing',
    background_name: 'minimal editorial backdrop with subtle texture, premium magazine look',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },
  {
    id: 'traditional_heritage',
    name: 'Heritage Courtyard',
    description: 'Warm heritage setting with realistic ambient light.',
    category: 'traditional',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'warm ambient heritage light, soft shadows, natural tones',
    background_name: 'heritage courtyard with arches and warm stone tones, shallow depth of field',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'traditional_temple_morning',
    name: 'Temple Morning',
    description: 'Soft morning courtyard scene with realistic stone texture.',
    category: 'traditional',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft morning light, gentle shadows, natural color, realistic contrast',
    background_name: 'temple courtyard with stone textures, shallow depth of field, calm atmosphere',
    style_pack: 'travel_journal',
    background_focus: 'sharper_bg',
  },

  // =========================
  // SUBTLE POSE VARIATIONS (recommend Pro + extra identity images)
  // =========================
  {
    id: 'pose_subtle_three_quarter',
    name: 'Subtle Pose: 3/4 Turn',
    description: 'Allows small body angle adjustment. Best with Pro + extra identity references.',
    category: 'studio',
    pose_mode: 'subtle',
    pose_name:
      'allow a subtle pose adjustment ONLY: slight 10–15° body turn, small head tilt, arms repositioned naturally; keep the same identity and facial structure exactly',
    lighting_name: 'studio softbox, medium contrast, realistic texture and shadows',
    background_name: 'clean studio background, shallow depth of field, 85mm portrait look',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'pose_subtle_handonhip',
    name: 'Subtle Pose: Hand on Hip',
    description: 'Allows one arm reposition. Best with Pro + extra identity references.',
    category: 'street',
    pose_mode: 'subtle',
    pose_name:
      'allow a subtle pose adjustment ONLY: move one hand to rest on hip, keep head angle similar; identity and face must stay exactly the same',
    lighting_name: 'soft overcast daylight, accurate colors',
    background_name: 'modern street background softly blurred, realistic bokeh',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },

  // =========================
  // IG STYLE PACK SPECIALS
  // =========================
  {
    id: 'ig_wellness_bed_golden',
    name: 'IG Wellness Bedroom (Golden)',
    description: 'Bright iPhone golden hour bedroom / wellness-mag vibe (balanced composition).',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'bright iPhone golden hour glow, airy light, soft shadows, no harsh contrast',
    background_name: 'cozy bedroom scene with warm sunlight and soft bokeh highlights, balanced lifestyle composition',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_paris_wall_candid',
    name: 'Paris Wall Candid (iPhone)',
    description: 'Street-candid iPhone look: slightly tilted frame, authentic textures, natural daylight.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft natural daylight, gentle highlights, realistic shadows',
    background_name: 'weathered stone wall and sidewalk textures, candid street framing, authentic urban details',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_doc_surveillance_crosswalk',
    name: 'Doc / Surveillance Crosswalk',
    description: 'High-angle documentary/surveillance vibe, gritty realism, muted colors.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'neutral overcast daylight, realistic exposure, minimal stylization',
    background_name: 'wide pedestrian crosswalk on textured asphalt, high-angle wide framing, documentary realism',
    style_pack: 'surveillance_doc',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_flash_party_myspace',
    name: 'Flash Party (MySpace)',
    description: 'Harsh on-camera flash, noisy shadows, crooked framing (no beauty retouch).',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'harsh on-camera flash, deep shadows, slight red-eye risk, noisy dark areas',
    background_name: 'night street or bar wall background, imperfect crop, candid party snapshot feel',
    style_pack: 'flash_party',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_travel_journal_tropical_walk',
    name: 'Travel Journal: Tropical Walk',
    description: 'Warm filtered light through leaves, light haze, subtle flare, travel journal vibe.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'warm filtered sunlight through leaves, light haze, subtle lens flare, natural shadows',
    background_name: 'tropical trees and ferns canopy, wooden platform/path, spontaneous travel-journal framing',
    style_pack: 'travel_journal',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_rainy_city_reflections',
    name: 'Rainy City Reflections (iPhone)',
    description: 'Candid iPhone street shot after rain: wet reflections, realistic haze, true-to-life textures.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'overcast rainy daylight, soft reflections, realistic wet highlights, no neon bloom halos',
    background_name: 'wet city sidewalk with puddle reflections, slightly hazy air, authentic street details, candid framing',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_elevator_mirror_editorial',
    name: 'Elevator Mirror (Editorial IG)',
    description: 'Clean elevator mirror vibe, premium but real; subtle grain, no CGI.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'mixed indoor lighting, slight green tint from fluorescents, realistic reflections and highlights',
    background_name: 'modern elevator interior with mirror reflections and brushed metal textures, realistic smudges, candid composition',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_outdoor_cafe_morning',
    name: 'Outdoor Café Morning (Candid)',
    description: 'Effortless phone-camera café moment: natural blur behind, calm morning light.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'cool spring morning daylight, soft shadows, natural highlights, realistic exposure',
    background_name: 'outdoor restaurant terrace with subtle background motion blur and bokeh, authentic city atmosphere',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_meadow_overcast_truecolor',
    name: 'Meadow Overcast (True Color)',
    description: 'Overcast meadow portrait for best fabric color accuracy + natural background realism.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft overcast daylight, very even illumination, accurate garment color, minimal specular hotspots',
    background_name: 'wild meadow with tall grass and soft natural depth of field, no overly perfect bokeh',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_flash_party_indoor_wall',
    name: 'Flash Party Indoor Wall',
    description: 'Harsh flash snapshot indoors (grainy shadows, authentic party look).',
    category: 'lifestyle',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'harsh direct on-camera flash, slightly blown highlights, noisy shadows, realistic skin texture',
    background_name: 'indoor wall with subtle decor and messy party realism, imperfect framing, candid snapshot',
    style_pack: 'flash_party',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_editorial_lace_backdrop',
    name: 'Editorial: Soft Lace Backdrop',
    description: 'Dreamy editorial lace/tulle backdrop with rich texture (realistic, not AI-perfect).',
    category: 'editorial',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'dramatic editorial key light with soft fill, deep shadows, textured highlights, no halos',
    background_name: 'layered lace or tulle curtains backdrop, soft focus depth, rich texture, modern editorial look',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_doc_mall_foodcourt_2005',
    name: 'Doc: 2005 Digicam Mall',
    description: 'Early-2000s digicam realism: harsh flash, noisy shadows, slightly waxy early processing.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'harsh on-camera flash, slightly blown highlights, noisy shadows, early-digital processing vibe',
    background_name: 'mall interior with food court tables, fluorescent lighting, candid awkward framing, documentary realism',
    style_pack: 'surveillance_doc',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_travel_window_train',
    name: 'Travel Journal: Train Window Light',
    description: 'Soft window light on a train, gentle motion + real travel atmosphere.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo (no pose change)',
    lighting_name: 'soft window daylight, subtle reflections, realistic highlights, natural shadow softness',
    background_name: 'train interior with window reflections and passing scenery softly blurred, authentic travel feel',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
]

export function getTryOnPresetV3(id: string): TryOnStylePreset | undefined {
  return TRYON_PRESETS_V3.find((p) => p.id === id)
}

export function getTryOnPresetCategoriesV3(): TryOnPresetCategory[] {
  return ['studio', 'street', 'outdoor', 'lifestyle', 'editorial', 'traditional']
}

export function getTryOnPresetListV3(): Array<{
  id: string
  name: string
  category: TryOnPresetCategory
  description: string
}> {
  return TRYON_PRESETS_V3.map((p) => ({
    id: p.id,
    name: p.name,
    category: p.category,
    description: p.description,
  }))
}


