import type { TryOnStylePreset, TryOnPresetCategory } from './types'

export const TRYON_PRESETS_V3: TryOnStylePreset[] = [
  // =========================
  // STUDIO PRESETS
  // =========================
  {
    id: 'studio_catalog_grey',
    name: 'Studio Catalog (Grey)',
    description: 'E-commerce product shot on seamless grey backdrop.',
    category: 'studio',
    pose_mode: 'locked',
    identity_lock: 'high',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'studio softbox key light at 45 degrees, soft fill, even illumination',
    background_name: 'seamless neutral grey studio backdrop, shot on Canon 5D with 85mm f/2',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'studio_catalog_white',
    name: 'Studio Catalog (White)',
    description: 'Clean white backdrop for true garment color.',
    category: 'studio',
    pose_mode: 'locked',
    identity_lock: 'high',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'high key studio lighting, soft diffused light, minimal shadows',
    background_name: 'seamless white cyclorama, shot on Sony A7R with 70mm f/2.8',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },
  {
    id: 'studio_beauty_clamshell',
    name: 'Beauty Clamshell',
    description: 'Beauty lighting with soft catchlights.',
    category: 'studio',
    pose_mode: 'locked',
    identity_lock: 'high',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'clamshell beauty lighting, soft key above, soft fill below chin',
    background_name: 'warm grey studio backdrop, shot on Canon 5D Mark IV with 100mm f/2.8 macro',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'studio_rim_moody',
    name: 'Moody Rim Light',
    description: 'Low-key studio with cinematic rim separation.',
    category: 'studio',
    pose_mode: 'locked',
    identity_lock: 'high',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'low key lighting, soft key at 45 degrees, subtle rim light from behind',
    background_name: 'deep charcoal backdrop, shot on Sony A7III with 85mm f/1.4, visible film grain',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },

  // =========================
  // STREET PRESETS
  // =========================
  {
    id: 'street_golden_hour',
    name: 'Golden Hour Street',
    description: 'Warm golden hour city street.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'golden hour warm side light, soft natural shadows',
    background_name: 'urban sidewalk with storefronts softly blurred, shot on iPhone 14 Pro',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'street_overcast_soft',
    name: 'Overcast Street',
    description: 'Soft overcast light for accurate colors.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft overcast daylight, even illumination, low contrast',
    background_name: 'modern city sidewalk, shot on iPhone 15, natural depth',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'street_flash_night',
    name: 'Night Street Flash',
    description: 'On-camera flash at night, party aesthetic.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'harsh on-camera flash, deep shadows, realistic flash falloff',
    background_name: 'night street with bokeh lights, shot on point-and-shoot digicam, noisy shadows',
    style_pack: 'flash_party',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'street_neon_cyber',
    name: 'Neon Night',
    description: 'Cinematic neon rim lights with wet reflections.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'neon rim lighting: cyan left magenta right, wet pavement reflections',
    background_name: 'night alley with neon signs in bokeh, shot on Sony A7 with 35mm f/1.4',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },

  // =========================
  // OUTDOOR PRESETS
  // =========================
  {
    id: 'outdoor_golden_field',
    name: 'Golden Field',
    description: 'Sunlit field with warm backlight.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'warm sunset backlight with natural fill, lens flare allowed',
    background_name: 'open field with tall grass, shot on Fujifilm X100V, 35mm',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'outdoor_overcast_portrait',
    name: 'Outdoor Overcast',
    description: 'Even overcast light for true colors.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft overcast daylight, even illumination, accurate color',
    background_name: 'park walkway with trees, shot on Canon 5D with 50mm f/1.8',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'outdoor_backlit_sunflare',
    name: 'Backlit Sunflare',
    description: 'Gentle backlight with controlled flare.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'golden backlight, subtle lens flare, soft fill on face',
    background_name: 'garden with warm bokeh, shot on Sony A7III with 85mm f/1.4',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },

  // =========================
  // LIFESTYLE PRESETS
  // =========================
  {
    id: 'lifestyle_cafe',
    name: 'Café Terrace',
    description: 'Cozy café with window light.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft window daylight, natural shadows, warm tones',
    background_name: 'café terrace with tables and chairs softly blurred, shot on iPhone 14',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'lifestyle_home_window',
    name: 'Home Window Light',
    description: 'Indoor home with soft natural light.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft window light, natural indoor shadows',
    background_name: 'minimal home interior with warm neutrals, shot on iPhone',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },

  // =========================
  // EDITORIAL PRESETS
  // =========================
  {
    id: 'editorial_architecture',
    name: 'Editorial Architecture',
    description: 'Premium editorial with clean architectural lines.',
    category: 'editorial',
    pose_mode: 'locked',
    identity_lock: 'high',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'directional editorial key light with subtle fill',
    background_name: 'modern architectural courtyard, shot on Hasselblad X2D with 80mm f/2.8',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'editorial_hard_light',
    name: 'Editorial Hard Light',
    description: 'Hard key light with strong shape.',
    category: 'editorial',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'hard key light from 45 degrees, crisp shadows, no fill',
    background_name: 'minimal editorial backdrop, shot on Canon 5D with 85mm',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },

  // =========================
  // TRADITIONAL PRESETS
  // =========================
  {
    id: 'traditional_heritage',
    name: 'Heritage Courtyard',
    description: 'Warm heritage setting with ambient light.',
    category: 'traditional',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'warm ambient heritage light, natural shadows',
    background_name: 'heritage courtyard with arches and stone, shot on Fujifilm X-T4',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'traditional_temple_morning',
    name: 'Temple Morning',
    description: 'Soft morning courtyard scene.',
    category: 'traditional',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft morning light, gentle shadows',
    background_name: 'temple courtyard with stone textures, shot on Canon 5D',
    style_pack: 'travel_journal',
    background_focus: 'sharper_bg',
  },

  // =========================
  // INSTAGRAM STYLE SPECIALS
  // =========================
  {
    id: 'ig_wellness_bed_golden',
    name: 'IG Wellness Bedroom',
    description: 'Bright iPhone golden hour bedroom vibe.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'bright iPhone golden hour glow, airy light',
    background_name: 'cozy bedroom with warm sunlight, shot on iPhone 15 Pro',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_paris_wall_candid',
    name: 'Paris Wall Candid',
    description: 'Street-candid iPhone look with authentic textures.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft natural daylight, realistic shadows',
    background_name: 'weathered Parisian stone wall, shot on iPhone',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_doc_surveillance_crosswalk',
    name: 'Doc Surveillance',
    description: 'Documentary surveillance aesthetic.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'neutral overcast daylight, flat contrast',
    background_name: 'wide pedestrian crosswalk, high angle, shot on wide-angle CCTV style',
    style_pack: 'surveillance_doc',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_flash_party_myspace',
    name: 'Flash Party MySpace',
    description: 'Harsh flash party aesthetic, no beauty retouch.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'harsh on-camera flash, deep shadows, red-eye possible',
    background_name: 'night street or bar, shot on 2000s digital camera',
    style_pack: 'flash_party',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_travel_journal_tropical',
    name: 'Travel Journal Tropical',
    description: 'Warm filtered light through leaves.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'warm filtered sunlight through leaves, light haze',
    background_name: 'tropical trees and ferns, shot on Fujifilm X100V',
    style_pack: 'travel_journal',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_rainy_city',
    name: 'Rainy City Reflections',
    description: 'Candid street shot after rain.',
    category: 'street',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'overcast rainy daylight, soft reflections',
    background_name: 'wet city sidewalk with puddle reflections, shot on iPhone',
    style_pack: 'candid_iphone',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_elevator_mirror',
    name: 'Elevator Mirror',
    description: 'Clean elevator mirror selfie vibe.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'mixed indoor fluorescent lighting, slight green tint',
    background_name: 'modern elevator with mirror and brushed metal, shot on iPhone',
    style_pack: 'editorial_ig',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_outdoor_cafe_morning',
    name: 'Outdoor Café Morning',
    description: 'Casual café morning phone capture.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'cool spring morning daylight, soft shadows',
    background_name: 'outdoor restaurant terrace, shot on iPhone, city atmosphere',
    style_pack: 'candid_iphone',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_meadow_overcast',
    name: 'Meadow Overcast',
    description: 'Overcast meadow for best fabric color.',
    category: 'outdoor',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft overcast daylight, even illumination',
    background_name: 'wild meadow with tall grass, shot on Fujifilm X-T4',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_flash_party_indoor',
    name: 'Flash Party Indoor',
    description: 'Harsh flash indoors, authentic party look.',
    category: 'lifestyle',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'harsh direct on-camera flash, noisy shadows',
    background_name: 'indoor wall with party decorations, shot on digicam',
    style_pack: 'flash_party',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_editorial_lace',
    name: 'Editorial Lace Backdrop',
    description: 'Dreamy editorial lace/tulle backdrop.',
    category: 'editorial',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'dramatic editorial key light with soft fill',
    background_name: 'layered lace curtains backdrop, shot on Hasselblad',
    style_pack: 'editorial_ig',
    background_focus: 'moderate_bokeh',
  },
  {
    id: 'ig_doc_mall_2005',
    name: 'Doc 2005 Digicam Mall',
    description: 'Early 2000s digicam mall aesthetic.',
    category: 'street',
    identity_lock: 'high',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'harsh flash with fluorescent mall lighting',
    background_name: 'mall interior with food court, shot on 2005 digital camera',
    style_pack: 'surveillance_doc',
    background_focus: 'sharper_bg',
  },
  {
    id: 'ig_travel_train_window',
    name: 'Train Window Light',
    description: 'Soft window light on a train.',
    category: 'lifestyle',
    pose_mode: 'locked',
    pose_name: 'keep pose exactly as in the subject photo',
    lighting_name: 'soft window daylight, subtle reflections',
    background_name: 'train interior with passing scenery blurred, shot on iPhone',
    style_pack: 'travel_journal',
    background_focus: 'moderate_bokeh',
  },
]

export function getTryOnPresetV3(id: string): TryOnStylePreset | undefined {
  return TRYON_PRESETS_V3.find((p) => p.id === id)
}

export function getTryOnPresetCategoriesV3(): TryOnPresetCategory[] {
  return ['studio', 'street', 'outdoor', 'lifestyle', 'editorial', 'traditional']
}

export function getTryOnPresetListV3(): Array<{
  id: string
  name: string
  category: TryOnPresetCategory
  description: string
}> {
  return TRYON_PRESETS_V3.map((p) => ({
    id: p.id,
    name: p.name,
    category: p.category,
    description: p.description,
  }))
}
